<div class="uk-container uk-container-center">
    <div class="uk-grid">
        <div class="uk-width-1-1">
            <div class="uk-panel uk-panel-box">
                <form class="uk-form uk-form-stacked" id="form-forgot" enctype="application/x-www-form-urlencoded" method="post">    
                    <legend class="uk-margin-large-top uk-margin-bottom">Acesse sua conta</legend>
                    <div class="uk-grid">
                        <div class="uk-width-1-1">
                            <div class="uk-form-row">
                                <label class="uk-form-label" for="f-input-email">Seu e-mail</label>
                                <div class="uk-form-controls">
                                    <div class="uk-form-icon uk-form-icon-flip uk-width-1-1">
                                        <i id="f-i-email"></i>
                                        <input type="text" name="f-input-email" id="f-input-email" class="uk-width-1-1" />
                                    </div>                     
                                </div>
                                <p>Envie-me um e-mail com um link para redefinir minha senha</p>
                            </div>
                        </div>
                    </div>

                    <div class="uk-grid">
                        <div class="uk-width-1-1">
                            <div class="uk-form-row">
                                <div class="uk-form-controls">
                                    <button type="submit" class="uk-button uk-button-primary uk-width-1-1">Acessar minha conta</button>
                                </div>
                            </div>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>