<section>
    <div class="uk-container uk-container-center">
        <div class="uk-grid uk-margin-large-top uk-margin-large-bottom">
            <div class="uk-width-1-1">
                <a href="/" class="uk-navbar-brand">LOCALHOST</a>
                <div class="uk-navbar-flip">
                    <ul class="uk-navbar-nav uk-hidden-small">
                        <li><a href="/">Página inicial</a></li>                        
                        <li><a href="/account/sign/up">Cadastre-se</a></li>
                        <li class="uk-active"><a href="/account/sign/in">Login</a></li>
                    </ul>
                    <a href="#offcanvas-right" class="uk-navbar-toggle uk-visible-small" data-uk-offcanvas></a>
                </div>
            </div>
        </div>
    </div>
</section>
<section>
    <div class="uk-container uk-container-center">
        <div class="uk-grid uk-margin-large-top uk-margin-large-bottom">
            <div class="uk-width-large-1-3 uk-width-medium-1-3 uk-width-small-1-2 uk-container-center">
                <div class="uk-panel uk-panel-box">
                    <form class="uk-form uk-form-stacked" id="form-signin" enctype="application/x-www-form-urlencoded" method="post">    
                        <legend class="uk-margin-large-top uk-margin-bottom">Acesse sua conta</legend>
                        <div class="uk-grid">
                                <div class="uk-width-1-1">
                                    <div class="uk-form-row">
                                        <label class="uk-form-label" for="f-input-email">Seu e-mail</label>
                                        <div class="uk-form-controls">
                                            <div class="uk-form-icon uk-form-icon-flip uk-width-1-1">
                                                <i id="f-i-email"></i>
                                                <input type="text" name="f-input-email" id="f-input-email" class="uk-width-1-1" />
                                            </div>                     
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                            <div class="uk-grid">
                                <div class="uk-width-1-1">
                                    <div class="uk-form-row">
                                        <label class="uk-form-label" for="f-input-password">Sua senha</label>
                                        <div class="uk-form-controls">
                                            <div class="uk-form-icon uk-form-icon-flip uk-width-1-1">
                                                <i id="f-i-password"></i>
                                                <input type="password" name="password" id="f-input-password" class="uk-width-1-1" />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        
                            <div class="uk-grid">
                                <div class="uk-width-1-1">
                            <div class="uk-form-row">
                                <div class="uk-form-controls">
                                    <button type="submit" class="uk-button uk-button-primary uk-width-1-1">Acessar minha conta</button>
                                </div>
                            </div>
                                </div>
                            </div>
                        
                        <div class="uk-form-row">
                            <div class="uk-form-controls">
                                <p class="uk-text-small"><a href="#">Esqueci minha senha</a></p>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>
</section>

<div id="offcanvas-right" class="uk-offcanvas" aria-hidden="true">
    <div class="uk-offcanvas-bar uk-offcanvas-bar-flip">
        <ul class="uk-nav uk-nav-offcanvas uk-nav-parent-icon" data-uk-nav="">
            <li class="uk-active"><a href="#">Página Inicial</a></li>
            <li><a href="/account/sign/up">Cadastre-se</a></li>
            <li><a href="/account/sign/in">Login</a></li>
        </ul>
    </div>
</div>