<nav class="uk-navbar uk-navbar-attached">
    <div class="uk-container uk-container-center">
        <a href="/" class="uk-navbar-brand">LOCALHOST</a>

        <div class="uk-navbar-flip">

            <a href="#menu-right" class="uk-navbar-toggle uk-visible-small" data-uk-offcanvas></a>

            <ul class="uk-navbar-nav uk-hidden-small">
                <li>
                    <a href="#">
                        <?php echo Zend_Auth::getInstance()->getIdentity()->firstname; ?>                        
                    </a>
                </li>
                <li class="uk-parent" data-uk-dropdown="">
                    <a href=""><i class="uk-icon-caret-down"></i></a>

                    <div class="uk-dropdown uk-dropdown-navbar">
                        <ul class="uk-nav uk-nav-navbar">
                            <li><a href="#">Minha conta</a></li>
                            <li class="uk-nav-divider"></li>
                            <li><a href="#">Configuração</a></li>
                            <li><a href="<?php echo $this->baseUrl('account/sign/out') ?>">Sair</a></li>                            
                            <li class="uk-nav-divider"></li>
                            <li><a href="#">Ajuda</a></li>
                            <li><a href="#">Reportar um problema</a></li>
                        </ul>
                    </div>

                </li>
            </ul>

        </div>
    </div>
</nav>

<section>
    <div class="uk-container uk-container-center">
        <div class="uk-grid uk-margin-large-top uk-margin-large-bottom">
            <div class="uk-width-1-1">
                <ul class="uk-breadcrumb">
                    <li><span>Minha Conta</span></li>
                </ul>

                <div class="uk-panel uk-panel-box">
                    <!-- This is a button toggling the modal -->
                    <button class="uk-button" data-uk-modal="{target:'#plan'}">Criar organização</button>
                </div>



            </div>
        </div>

        <div class="uk-panel uk-panel-box" id="id_list_configuration"></div>

    </div>
</section>

<div id="plan" class="uk-modal">
    <div class="uk-modal-dialog">
        <form class="uk-form uk-form-stacked" id="form-organization" autocomplete="on">

            <div class="uk-grid">
                <div class="uk-width-1-1">
                    <div class="uk-form-row">
                        <label class="uk-form-label" for="f-input-name">Nome da Organização</label>
                        <div class="uk-form-controls">
                            <input type="text" name="f-input-name" id="f-input-name" class="uk-width-1-1" maxlength="32" autofocus="" />
                        </div>
                    </div>
                </div>
            </div>
            <div class="uk-grid">
                <div class="uk-width-1-1">
                    <div class="uk-form-row">
                        <div class="uk-form-controls">
                            <button type="submit" class="uk-button">Criar organização</button>           
                        </div>
                    </div>
                </div>
            </div>

        </form>
    </div>
</div>


<!-- This is the off-canvas sidebar -->
<div id="menu-right" class="uk-offcanvas">
    <div class="uk-offcanvas-bar uk-offcanvas-bar-flip">
        <ul class="uk-nav uk-nav-offcanvas" data-uk-nav>
            
        </ul>
    </div>
</div>