<nav class="uk-navbar uk-navbar-attached">
    <div class="uk-container uk-container-center">
        <a class="uk-navbar-brand" href="#">LOCALHOST</a>

        <ul class="uk-navbar-nav uk-navbar-center uk-hidden-small">
                <li><a href="<?php echo $this->baseUrl('app/finance/overview') ?>">Visão Geral</a></li>
                <li><a href="<?php echo $this->baseUrl('app/finance/bills') ?>">Lançamentos</a></li>                
            </ul>
        
        <div class="uk-navbar-content">
            <button class="uk-button uk-button-primary" id="new_register" data-uk-modal="{target:'#my-id'}">Novo Registro</button>
        </div>
        
        <div class="uk-navbar-flip">

            <a href="#menu-right" class="uk-navbar-toggle uk-visible-small" data-uk-offcanvas></a>

            <ul class="uk-navbar-nav uk-hidden-small">
                <li>
                    <a href="#">
                        <?php echo Zend_Auth::getInstance()->getIdentity()->firstname; ?>                        
                    </a>
                </li>
                <li class="uk-parent" data-uk-dropdown="">
                    <a href=""><i class="uk-icon-caret-down"></i></a>

                    <div class="uk-dropdown uk-dropdown-navbar">
                        <ul class="uk-nav uk-nav-navbar">
                            <li><a href="#">Minha conta</a></li>
                            <li class="uk-nav-divider"></li>
                            <li><a href="#">Configuração</a></li>
                            <li><a href="<?php echo $this->baseUrl('account/sign/out') ?>">Sair</a></li>                            
                            <li class="uk-nav-divider"></li>
                            <li><a href="#">Ajuda</a></li>
                            <li><a href="#">Reportar um problema</a></li>
                        </ul>
                    </div>

                </li>
            </ul>

        </div>
    </div>
</nav>


<section>
    <div class="uk-container uk-container-center">
        <div class="uk-grid uk-margin-large-top uk-margin-large-bottom">
            <div class="uk-width-1-1">
                <div class="uk-panel uk-panel-box uk-panel-box-secondary">
                    <div class="uk-button-group">

                        <label class="uk-button uk-text-bold">
                            <input type="checkbox" id="select-all" />                           
                        </label>

                        <!-- This is the container enabling the JavaScript -->
                        <div data-uk-dropdown="{mode:'click'}">

                            <!-- This is the button toggling the dropdown -->
                            <a href="" class="uk-button"><i class="uk-icon-caret-down"></i></a>

                            <!-- This is the dropdown -->
                            <div class="uk-dropdown uk-dropdown-small">
                                <ul class="uk-nav uk-nav-dropdown">
                                    <li><a href="">Tudo</a></li>
                                    <li><a href="">Nenhum</a></li>
                                </ul>
                            </div>

                        </div>
                    </div>
                    <button class="uk-button uk-margin-left uk-margin-right" id="refresh"><i class="uk-icon-refresh uk-margin-left uk-margin-right"></i></button>
                    <button class="uk-button uk-hidden" id="alter"><i class="uk-icon-edit"></i></button>
                    <button class="uk-button uk-hidden" id="delete"><i class="uk-icon-trash"></i></button>
                    <div class="uk-button-group uk-align-right">

                        <button class="uk-button"><i class="uk-icon-cog"></i></button>

                        <!-- This is the container enabling the JavaScript -->
                        <div data-uk-dropdown="{mode:'click'}">

                            <!-- This is the button toggling the dropdown -->
                            <a href="" class="uk-button"><i class="uk-icon-caret-down"></i></a>

                            <!-- This is the dropdown -->
                            <div class="uk-dropdown uk-dropdown-small">
                                <ul class="uk-nav uk-nav-dropdown">
                                    <li><a href="">Tudo</a></li>
                                    <li><a href="">Nenhum</a></li>
                                </ul>
                            </div>

                        </div>
                    </div>
                    <button class="uk-button uk-align-right"><i class="uk-icon-chevron-right"></i></button>
                    <button class="uk-button uk-align-right"><i class="uk-icon-chevron-left"></i></button>
                    <hr />
                    <table id="id_bills" class="uk-table uk-table-hover">
                        <thead>
                            <tr>
                                <th></th>
                                <th>Descrição</th>
                                <th>Vencimento</th>
                                <th>Valor</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php echo $this->trTable; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>




<div class="uk-modal" id="my-id">
    <div class="uk-modal-dialog">
        <div class="uk-modal-header">Contas</div>
        <form class="uk-form uk-form-stacked">
            <div class="uk-form-row uk-hidden">
                <label class="uk-form-label" for="">ID</label>
                <div class="uk-form-controls">
                    <input type="text" id="form_bills_id" placeholder="...">
                </div>
            </div>
            <div class="uk-form-row">
                <label class="uk-form-label" for="">Descrição</label>
                <div class="uk-form-controls">
                    <input type="text" id="form_bills_description" placeholder="João da Silva">
                </div>
            </div>
            <div class="uk-form-row">
                <label class="uk-form-label" for="">Data do vencimento</label>
                <div class="uk-form-controls">
                    <input type="date" id="form_bills_due_date" placeholder="DD/MM/AAAA">
                </div>
            </div>
            <div class="uk-form-row">
                <label class="uk-form-label" for="">Valor</label>
                <div class="uk-form-controls">
                    <input type="text" id="form_bills_value" placeholder="0,00">
                </div>
            </div>

        </form>
        <div class="uk-modal-footer uk-text-right">
            <button type="button" class="uk-button uk-modal-close">Cancelar</button>
            <button type="button" class="uk-button uk-button-primary" id="button_save_bills">Salvar</button>
        </div>
    </div>
</div>

<!-- This is the off-canvas sidebar -->
<div id="menu-right" class="uk-offcanvas">
    <div class="uk-offcanvas-bar uk-offcanvas-bar-flip">
        <ul class="uk-nav uk-nav-offcanvas" data-uk-nav>            
            <li><a href="<?php echo $this->baseUrl('app/finance/overview') ?>">Visão Geral</a></li>
            <li><a href="<?php echo $this->baseUrl('app/finance/bills') ?>">Lançamentos</a></li>                
            <li class="uk-nav-divider"></li>
            <li><a href="#my-id" data-uk-modal>Novo Registro</a></li>
            <li class="uk-nav-divider"></li>
            <li><a href="">Sair</a></li>
        </ul>
    </div>
</div>