<?php echo $this->doctype('XHTML1_STRICT') ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pt-BR" >
    <head>  
        <?php
        echo $this->headTitle("LOCALHOST");

        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1')
                ->setHttpEquiv('Content-Type', 'text/html;charset=UTF-8')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
                ->appendHttpEquiv('language', 'pt-BR')
                ->appendHttpEquiv('Author', 'Department web')
                ->appendHttpEquiv('reply-to', '...@gmail.com')
                ->appendHttpEquiv('expires', '-1')
                ->appendHttpEquiv('pragma', 'no-cache')
                ->appendHttpEquiv('Cache-Control', 'no-cache')
                ->appendName('robots', 'index, follow')
                ->appendName('DC.title', 'LOCALHOST')
                ->appendName('description', 'description');

        echo $this->headLink()
                ->appendStylesheet($this->baseUrl('/public/framework/css/uikit.css'))
                ->appendStylesheet($this->baseUrl('/public/framework/css/components/tooltip.css'))
                ->appendStylesheet($this->baseUrl('/public/framework/css/components/upload.almost-flat.css'));
        ?>

    </head>
    <body>

        <?php echo $this->layout()->content; ?>

        <footer class="footer">
            <div class="uk-block">
                <div class="uk-container uk-container-center">
                    <div class="uk-grid uk-grid-match" data-uk-grid-margin="">
                        <div class="uk-width-medium-1-3 uk-text-center ">
                            <div class="uk-panel">
                                <h3>Empresa</h3>
                                <ul class="uk-list uk-list-space">
                                    <li>Sobre nós</li>
                                    <li>Trabalhe conosco</li>
                                </ul>
                            </div>
                        </div>
                        <div class="uk-width-medium-1-3 uk-text-center ">
                            <div class="uk-panel">
                                <h3>Nossos serviços</h3>
                                <ul class="uk-list uk-list-space">
                                    <li>Conta pessoal</li>
                                    <li>Conta empresarial</li>
                                </ul>
                            </div>
                        </div>
                        <div class="uk-width-medium-1-3 uk-text-center ">
                            <div class="uk-panel">
                                <h3>Suporte</h3>
                                <ul class="uk-list uk-list-space">
                                    <li>Central de ajuda</li>
                                    <li>Contato</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="uk-block">
                <div class="uk-container uk-container-center uk-text-center">
                    <p>LOCALHOST &COPY; 2015</p><p>Todos os direitos reservados</p>
                    <ul class="uk-subnav uk-subnav-line uk-flex-center">
                        <li><a href="">Termos de uso</a></li>
                        <li><a href="">Política de privacidade</a></li>
                    </ul>
                </div>
            </div>
        </footer>

        <?php
        echo $this->headScript()
                ->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js')
                ->appendFile('/public/framework/js/uikit.min.js')
                ->appendFile('/public/framework/js/components/form-password.js');
        echo $this->teste;
        ?>

        <script>
            (function (i, s, o, g, r, a, m) {
                i['GoogleAnalyticsObject'] = r;
                i[r] = i[r] || function () {
                    (i[r].q = i[r].q || []).push(arguments)
                }, i[r].l = 1 * new Date();
                a = s.createElement(o),
                        m = s.getElementsByTagName(o)[0];
                a.async = 1;
                a.src = g;
                m.parentNode.insertBefore(a, m)
            })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

            ga('create', 'UA-63554195-1', 'auto');
            ga('send', 'pageview');
        </script>
    </body>
</html>