<?php echo $this->doctype('XHTML1_STRICT') ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pt-BR" >
    <head>  
        <?php
        echo $this->headTitle('LOCALHOST');

        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1')
                ->setHttpEquiv('Content-Type', 'text/html;charset=UTF-8')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
                ->appendHttpEquiv('language', 'pt-BR')
                ->appendHttpEquiv('Author', 'Department web')
                ->appendHttpEquiv('reply-to', '...@gmail.com')
                ->appendHttpEquiv('expires', '-1')
                ->appendHttpEquiv('pragma', 'no-cache')
                ->appendHttpEquiv('Cache-Control', 'no-cache')
                ->appendName('robots', 'index, follow')
                ->appendName('DC.title', 'LOCALHOST')
                ->appendName('description', 'description');

        echo $this->headLink()
                ->appendStylesheet($this->baseUrl('/public/framework/css/uikit.css'));
        ?>

    </head>
    <body>     

        <?php echo $this->layout()->content; ?>

        <?php
        /**
         *  jQuery (necessary for Bootstrap's JavaScript plugins)
         *  Include all compiled plugins (below), or include individual files as needed 
         */
        echo $this->headScript()
                ->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js')
                ->appendFile($this->baseUrl('/public/framework/js/uikit.min.js'));
        ?>
        <script>
            (function (i, s, o, g, r, a, m) {
                i['GoogleAnalyticsObject'] = r;
                i[r] = i[r] || function () {
                    (i[r].q = i[r].q || []).push(arguments)
                }, i[r].l = 1 * new Date();
                a = s.createElement(o),
                        m = s.getElementsByTagName(o)[0];
                a.async = 1;
                a.src = g;
                m.parentNode.insertBefore(a, m)
            })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

            ga('create', 'UA-63554195-1', 'auto');
            ga('send', 'pageview');
        </script>
    </body>
</html>